server:
  port: 8080

spring:
  application:
    name: Gateway
  main:
    allow-circular-references: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: Security
          uri: lb://Security
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
        - id: Department
          uri: lb://Department
          predicates:
            - Path=/department/**
          filters:
            - AuthenticationFilter    
            
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: warn
